"""quiz tables

Revision ID: 06a6911e3938
Revises: f26abcf0d0de
Create Date: 2026-02-26 22:51:10.391089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a6911e3938'
down_revision = 'f26abcf0d0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
